// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getHSLocalMdsStress
double getHSLocalMdsStress(arma::mat& data, const arma::vec& confVec, arma::imat& neighborhood, arma::imat& notNeighborhood, unsigned int& Rn, double& tt, double& Gamma);
RcppExport SEXP _NLDR_getHSLocalMdsStress(SEXP dataSEXP, SEXP confVecSEXP, SEXP neighborhoodSEXP, SEXP notNeighborhoodSEXP, SEXP RnSEXP, SEXP ttSEXP, SEXP GammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type confVec(confVecSEXP);
    Rcpp::traits::input_parameter< arma::imat& >::type neighborhood(neighborhoodSEXP);
    Rcpp::traits::input_parameter< arma::imat& >::type notNeighborhood(notNeighborhoodSEXP);
    Rcpp::traits::input_parameter< unsigned int& >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< double& >::type tt(ttSEXP);
    Rcpp::traits::input_parameter< double& >::type Gamma(GammaSEXP);
    rcpp_result_gen = Rcpp::wrap(getHSLocalMdsStress(data, confVec, neighborhood, notNeighborhood, Rn, tt, Gamma));
    return rcpp_result_gen;
END_RCPP
}
// getHSLocalMdsStressGradient
arma::vec getHSLocalMdsStressGradient(arma::mat& data, const arma::vec& confVec, arma::imat& neighborhood, arma::imat& notNeighborhood, unsigned int& Rn, double& tt, double& Gamma);
RcppExport SEXP _NLDR_getHSLocalMdsStressGradient(SEXP dataSEXP, SEXP confVecSEXP, SEXP neighborhoodSEXP, SEXP notNeighborhoodSEXP, SEXP RnSEXP, SEXP ttSEXP, SEXP GammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type confVec(confVecSEXP);
    Rcpp::traits::input_parameter< arma::imat& >::type neighborhood(neighborhoodSEXP);
    Rcpp::traits::input_parameter< arma::imat& >::type notNeighborhood(notNeighborhoodSEXP);
    Rcpp::traits::input_parameter< unsigned int& >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< double& >::type tt(ttSEXP);
    Rcpp::traits::input_parameter< double& >::type Gamma(GammaSEXP);
    rcpp_result_gen = Rcpp::wrap(getHSLocalMdsStressGradient(data, confVec, neighborhood, notNeighborhood, Rn, tt, Gamma));
    return rcpp_result_gen;
END_RCPP
}
// getNeighborhoodMatrix
arma::imat getNeighborhoodMatrix(arma::mat& data, int k, bool symmetric);
RcppExport SEXP _NLDR_getNeighborhoodMatrix(SEXP dataSEXP, SEXP kSEXP, SEXP symmetricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    rcpp_result_gen = Rcpp::wrap(getNeighborhoodMatrix(data, k, symmetric));
    return rcpp_result_gen;
END_RCPP
}
// getNeighborhoodVector
arma::ivec getNeighborhoodVector(arma::vec& data, int k);
RcppExport SEXP _NLDR_getNeighborhoodVector(SEXP dataSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(getNeighborhoodVector(data, k));
    return rcpp_result_gen;
END_RCPP
}
// getEuclideanDistanceMatrix
arma::mat getEuclideanDistanceMatrix(arma::mat& data);
RcppExport SEXP _NLDR_getEuclideanDistanceMatrix(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(getEuclideanDistanceMatrix(data));
    return rcpp_result_gen;
END_RCPP
}
// getParameterT
double getParameterT(arma::mat& data, arma::imat& neighborhood, double tau);
RcppExport SEXP _NLDR_getParameterT(SEXP dataSEXP, SEXP neighborhoodSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::imat& >::type neighborhood(neighborhoodSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(getParameterT(data, neighborhood, tau));
    return rcpp_result_gen;
END_RCPP
}
// getHSMdsStress
double getHSMdsStress(arma::mat& data, const arma::vec& confVec, unsigned int& Rn, double& Gamma);
RcppExport SEXP _NLDR_getHSMdsStress(SEXP dataSEXP, SEXP confVecSEXP, SEXP RnSEXP, SEXP GammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type confVec(confVecSEXP);
    Rcpp::traits::input_parameter< unsigned int& >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< double& >::type Gamma(GammaSEXP);
    rcpp_result_gen = Rcpp::wrap(getHSMdsStress(data, confVec, Rn, Gamma));
    return rcpp_result_gen;
END_RCPP
}
// getHSMdsStressNormalized
double getHSMdsStressNormalized(arma::mat& data, const arma::vec& confVec, unsigned int& Rn, double& Gamma);
RcppExport SEXP _NLDR_getHSMdsStressNormalized(SEXP dataSEXP, SEXP confVecSEXP, SEXP RnSEXP, SEXP GammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type confVec(confVecSEXP);
    Rcpp::traits::input_parameter< unsigned int& >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< double& >::type Gamma(GammaSEXP);
    rcpp_result_gen = Rcpp::wrap(getHSMdsStressNormalized(data, confVec, Rn, Gamma));
    return rcpp_result_gen;
END_RCPP
}
// getHSMdsStressGradient
arma::vec getHSMdsStressGradient(arma::mat& data, const arma::vec& confVec, unsigned int& Rn, double& Gamma);
RcppExport SEXP _NLDR_getHSMdsStressGradient(SEXP dataSEXP, SEXP confVecSEXP, SEXP RnSEXP, SEXP GammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type confVec(confVecSEXP);
    Rcpp::traits::input_parameter< unsigned int& >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< double& >::type Gamma(GammaSEXP);
    rcpp_result_gen = Rcpp::wrap(getHSMdsStressGradient(data, confVec, Rn, Gamma));
    return rcpp_result_gen;
END_RCPP
}
// RcppGetLocalContinuityMetaCriterion
Rcpp::List RcppGetLocalContinuityMetaCriterion(arma::mat& data, arma::mat& conf, int Rn, int k);
RcppExport SEXP _NLDR_RcppGetLocalContinuityMetaCriterion(SEXP dataSEXP, SEXP confSEXP, SEXP RnSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type conf(confSEXP);
    Rcpp::traits::input_parameter< int >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppGetLocalContinuityMetaCriterion(data, conf, Rn, k));
    return rcpp_result_gen;
END_RCPP
}
// RcppGetLocalContinuityMetaCriterionByVector
Rcpp::List RcppGetLocalContinuityMetaCriterionByVector(arma::mat& data, arma::mat& conf, int Rn, int k);
RcppExport SEXP _NLDR_RcppGetLocalContinuityMetaCriterionByVector(SEXP dataSEXP, SEXP confSEXP, SEXP RnSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type conf(confSEXP);
    Rcpp::traits::input_parameter< int >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppGetLocalContinuityMetaCriterionByVector(data, conf, Rn, k));
    return rcpp_result_gen;
END_RCPP
}
// OptimHSMds
Rcpp::List OptimHSMds(arma::mat& data, arma::mat& conf, unsigned int& Rn, double& Gamma, int& maxIt, const std::string& optMethod, unsigned int optTrace, unsigned int optReport);
RcppExport SEXP _NLDR_OptimHSMds(SEXP dataSEXP, SEXP confSEXP, SEXP RnSEXP, SEXP GammaSEXP, SEXP maxItSEXP, SEXP optMethodSEXP, SEXP optTraceSEXP, SEXP optReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type conf(confSEXP);
    Rcpp::traits::input_parameter< unsigned int& >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< double& >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< int& >::type maxIt(maxItSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type optMethod(optMethodSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type optTrace(optTraceSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type optReport(optReportSEXP);
    rcpp_result_gen = Rcpp::wrap(OptimHSMds(data, conf, Rn, Gamma, maxIt, optMethod, optTrace, optReport));
    return rcpp_result_gen;
END_RCPP
}
// OptimHSLocalMds
Rcpp::List OptimHSLocalMds(arma::mat& data, arma::mat& conf, arma::imat& neighborhood, arma::imat& notNeighborhood, unsigned int& Rn, double& tt, double& Gamma, int& maxIt, const std::string& optMethod, unsigned int optTrace, unsigned int optReport);
RcppExport SEXP _NLDR_OptimHSLocalMds(SEXP dataSEXP, SEXP confSEXP, SEXP neighborhoodSEXP, SEXP notNeighborhoodSEXP, SEXP RnSEXP, SEXP ttSEXP, SEXP GammaSEXP, SEXP maxItSEXP, SEXP optMethodSEXP, SEXP optTraceSEXP, SEXP optReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type conf(confSEXP);
    Rcpp::traits::input_parameter< arma::imat& >::type neighborhood(neighborhoodSEXP);
    Rcpp::traits::input_parameter< arma::imat& >::type notNeighborhood(notNeighborhoodSEXP);
    Rcpp::traits::input_parameter< unsigned int& >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< double& >::type tt(ttSEXP);
    Rcpp::traits::input_parameter< double& >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< int& >::type maxIt(maxItSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type optMethod(optMethodSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type optTrace(optTraceSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type optReport(optReportSEXP);
    rcpp_result_gen = Rcpp::wrap(OptimHSLocalMds(data, conf, neighborhood, notNeighborhood, Rn, tt, Gamma, maxIt, optMethod, optTrace, optReport));
    return rcpp_result_gen;
END_RCPP
}
// HSMDS
Rcpp::List HSMDS(arma::mat& data, Rcpp::Nullable<arma::mat> conf, unsigned int Rn, unsigned int Kquality, bool verbose, bool applyHyperbolicSmoothing, double gamma, unsigned int n_gamma, double rho, int maxIt, const std::string optMethod, unsigned int optTrace, unsigned int optReport);
RcppExport SEXP _NLDR_HSMDS(SEXP dataSEXP, SEXP confSEXP, SEXP RnSEXP, SEXP KqualitySEXP, SEXP verboseSEXP, SEXP applyHyperbolicSmoothingSEXP, SEXP gammaSEXP, SEXP n_gammaSEXP, SEXP rhoSEXP, SEXP maxItSEXP, SEXP optMethodSEXP, SEXP optTraceSEXP, SEXP optReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type conf(confSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type Kquality(KqualitySEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type applyHyperbolicSmoothing(applyHyperbolicSmoothingSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_gamma(n_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type maxIt(maxItSEXP);
    Rcpp::traits::input_parameter< const std::string >::type optMethod(optMethodSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type optTrace(optTraceSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type optReport(optReportSEXP);
    rcpp_result_gen = Rcpp::wrap(HSMDS(data, conf, Rn, Kquality, verbose, applyHyperbolicSmoothing, gamma, n_gamma, rho, maxIt, optMethod, optTrace, optReport));
    return rcpp_result_gen;
END_RCPP
}
// HSlocalMDS
Rcpp::List HSlocalMDS(arma::mat& data, Rcpp::Nullable<arma::mat> conf, unsigned int Rn, unsigned int Kproj, unsigned int Kquality, bool verbose, bool selectBetterUnitFree, double smallerUnitFree, unsigned int n_t, double ratio, bool applyHyperbolicSmoothing, double gamma, unsigned int n_gamma, double rho, int maxIt, const std::string optMethod, unsigned int optTrace, unsigned int optReport);
RcppExport SEXP _NLDR_HSlocalMDS(SEXP dataSEXP, SEXP confSEXP, SEXP RnSEXP, SEXP KprojSEXP, SEXP KqualitySEXP, SEXP verboseSEXP, SEXP selectBetterUnitFreeSEXP, SEXP smallerUnitFreeSEXP, SEXP n_tSEXP, SEXP ratioSEXP, SEXP applyHyperbolicSmoothingSEXP, SEXP gammaSEXP, SEXP n_gammaSEXP, SEXP rhoSEXP, SEXP maxItSEXP, SEXP optMethodSEXP, SEXP optTraceSEXP, SEXP optReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type conf(confSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type Kproj(KprojSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type Kquality(KqualitySEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type selectBetterUnitFree(selectBetterUnitFreeSEXP);
    Rcpp::traits::input_parameter< double >::type smallerUnitFree(smallerUnitFreeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_t(n_tSEXP);
    Rcpp::traits::input_parameter< double >::type ratio(ratioSEXP);
    Rcpp::traits::input_parameter< bool >::type applyHyperbolicSmoothing(applyHyperbolicSmoothingSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_gamma(n_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type maxIt(maxItSEXP);
    Rcpp::traits::input_parameter< const std::string >::type optMethod(optMethodSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type optTrace(optTraceSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type optReport(optReportSEXP);
    rcpp_result_gen = Rcpp::wrap(HSlocalMDS(data, conf, Rn, Kproj, Kquality, verbose, selectBetterUnitFree, smallerUnitFree, n_t, ratio, applyHyperbolicSmoothing, gamma, n_gamma, rho, maxIt, optMethod, optTrace, optReport));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NLDR_getHSLocalMdsStress", (DL_FUNC) &_NLDR_getHSLocalMdsStress, 7},
    {"_NLDR_getHSLocalMdsStressGradient", (DL_FUNC) &_NLDR_getHSLocalMdsStressGradient, 7},
    {"_NLDR_getNeighborhoodMatrix", (DL_FUNC) &_NLDR_getNeighborhoodMatrix, 3},
    {"_NLDR_getNeighborhoodVector", (DL_FUNC) &_NLDR_getNeighborhoodVector, 2},
    {"_NLDR_getEuclideanDistanceMatrix", (DL_FUNC) &_NLDR_getEuclideanDistanceMatrix, 1},
    {"_NLDR_getParameterT", (DL_FUNC) &_NLDR_getParameterT, 3},
    {"_NLDR_getHSMdsStress", (DL_FUNC) &_NLDR_getHSMdsStress, 4},
    {"_NLDR_getHSMdsStressNormalized", (DL_FUNC) &_NLDR_getHSMdsStressNormalized, 4},
    {"_NLDR_getHSMdsStressGradient", (DL_FUNC) &_NLDR_getHSMdsStressGradient, 4},
    {"_NLDR_RcppGetLocalContinuityMetaCriterion", (DL_FUNC) &_NLDR_RcppGetLocalContinuityMetaCriterion, 4},
    {"_NLDR_RcppGetLocalContinuityMetaCriterionByVector", (DL_FUNC) &_NLDR_RcppGetLocalContinuityMetaCriterionByVector, 4},
    {"_NLDR_OptimHSMds", (DL_FUNC) &_NLDR_OptimHSMds, 8},
    {"_NLDR_OptimHSLocalMds", (DL_FUNC) &_NLDR_OptimHSLocalMds, 11},
    {"_NLDR_HSMDS", (DL_FUNC) &_NLDR_HSMDS, 13},
    {"_NLDR_HSlocalMDS", (DL_FUNC) &_NLDR_HSlocalMDS, 18},
    {NULL, NULL, 0}
};

RcppExport void R_init_NLDR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
