// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getNeighborhoodMatrix
arma::imat getNeighborhoodMatrix(arma::mat& data, int k, bool symmetric);
RcppExport SEXP _RcppHSLocalMDS_getNeighborhoodMatrix(SEXP dataSEXP, SEXP kSEXP, SEXP symmetricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    rcpp_result_gen = Rcpp::wrap(getNeighborhoodMatrix(data, k, symmetric));
    return rcpp_result_gen;
END_RCPP
}
// getNeighborhoodVector
arma::ivec getNeighborhoodVector(arma::vec& data, int k);
RcppExport SEXP _RcppHSLocalMDS_getNeighborhoodVector(SEXP dataSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(getNeighborhoodVector(data, k));
    return rcpp_result_gen;
END_RCPP
}
// getEuclideanDistanceMatrix
arma::mat getEuclideanDistanceMatrix(arma::mat& data);
RcppExport SEXP _RcppHSLocalMDS_getEuclideanDistanceMatrix(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(getEuclideanDistanceMatrix(data));
    return rcpp_result_gen;
END_RCPP
}
// getParameterT
double getParameterT(arma::mat& data, arma::imat& neighborhood, double tau);
RcppExport SEXP _RcppHSLocalMDS_getParameterT(SEXP dataSEXP, SEXP neighborhoodSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::imat& >::type neighborhood(neighborhoodSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(getParameterT(data, neighborhood, tau));
    return rcpp_result_gen;
END_RCPP
}
// getHSLocalMdsStress
double getHSLocalMdsStress(arma::mat& data, const arma::vec& confVec, arma::imat& neighborhood, arma::imat& notNeighborhood, unsigned int& Rn, double& tt, double& Gamma);
RcppExport SEXP _RcppHSLocalMDS_getHSLocalMdsStress(SEXP dataSEXP, SEXP confVecSEXP, SEXP neighborhoodSEXP, SEXP notNeighborhoodSEXP, SEXP RnSEXP, SEXP ttSEXP, SEXP GammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type confVec(confVecSEXP);
    Rcpp::traits::input_parameter< arma::imat& >::type neighborhood(neighborhoodSEXP);
    Rcpp::traits::input_parameter< arma::imat& >::type notNeighborhood(notNeighborhoodSEXP);
    Rcpp::traits::input_parameter< unsigned int& >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< double& >::type tt(ttSEXP);
    Rcpp::traits::input_parameter< double& >::type Gamma(GammaSEXP);
    rcpp_result_gen = Rcpp::wrap(getHSLocalMdsStress(data, confVec, neighborhood, notNeighborhood, Rn, tt, Gamma));
    return rcpp_result_gen;
END_RCPP
}
// getHSLocalMdsStressGradient
arma::vec getHSLocalMdsStressGradient(arma::mat& data, const arma::vec& confVec, arma::imat& neighborhood, arma::imat& notNeighborhood, unsigned int& Rn, double& tt, double& Gamma);
RcppExport SEXP _RcppHSLocalMDS_getHSLocalMdsStressGradient(SEXP dataSEXP, SEXP confVecSEXP, SEXP neighborhoodSEXP, SEXP notNeighborhoodSEXP, SEXP RnSEXP, SEXP ttSEXP, SEXP GammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type confVec(confVecSEXP);
    Rcpp::traits::input_parameter< arma::imat& >::type neighborhood(neighborhoodSEXP);
    Rcpp::traits::input_parameter< arma::imat& >::type notNeighborhood(notNeighborhoodSEXP);
    Rcpp::traits::input_parameter< unsigned int& >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< double& >::type tt(ttSEXP);
    Rcpp::traits::input_parameter< double& >::type Gamma(GammaSEXP);
    rcpp_result_gen = Rcpp::wrap(getHSLocalMdsStressGradient(data, confVec, neighborhood, notNeighborhood, Rn, tt, Gamma));
    return rcpp_result_gen;
END_RCPP
}
// getHSMdsStress
double getHSMdsStress(arma::mat& data, const arma::vec& confVec, unsigned int& Rn, double& Gamma);
RcppExport SEXP _RcppHSLocalMDS_getHSMdsStress(SEXP dataSEXP, SEXP confVecSEXP, SEXP RnSEXP, SEXP GammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type confVec(confVecSEXP);
    Rcpp::traits::input_parameter< unsigned int& >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< double& >::type Gamma(GammaSEXP);
    rcpp_result_gen = Rcpp::wrap(getHSMdsStress(data, confVec, Rn, Gamma));
    return rcpp_result_gen;
END_RCPP
}
// getHSMdsStressNormalized
double getHSMdsStressNormalized(arma::mat& data, const arma::vec& confVec, unsigned int& Rn, double& Gamma);
RcppExport SEXP _RcppHSLocalMDS_getHSMdsStressNormalized(SEXP dataSEXP, SEXP confVecSEXP, SEXP RnSEXP, SEXP GammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type confVec(confVecSEXP);
    Rcpp::traits::input_parameter< unsigned int& >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< double& >::type Gamma(GammaSEXP);
    rcpp_result_gen = Rcpp::wrap(getHSMdsStressNormalized(data, confVec, Rn, Gamma));
    return rcpp_result_gen;
END_RCPP
}
// getHSMdsStressGradient
arma::vec getHSMdsStressGradient(arma::mat& data, const arma::vec& confVec, unsigned int& Rn, double& Gamma);
RcppExport SEXP _RcppHSLocalMDS_getHSMdsStressGradient(SEXP dataSEXP, SEXP confVecSEXP, SEXP RnSEXP, SEXP GammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type confVec(confVecSEXP);
    Rcpp::traits::input_parameter< unsigned int& >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< double& >::type Gamma(GammaSEXP);
    rcpp_result_gen = Rcpp::wrap(getHSMdsStressGradient(data, confVec, Rn, Gamma));
    return rcpp_result_gen;
END_RCPP
}
// RcppGetLocalContinuityMetaCriterion
Rcpp::List RcppGetLocalContinuityMetaCriterion(arma::mat& data, arma::mat& conf, int Rn, int k);
RcppExport SEXP _RcppHSLocalMDS_RcppGetLocalContinuityMetaCriterion(SEXP dataSEXP, SEXP confSEXP, SEXP RnSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type conf(confSEXP);
    Rcpp::traits::input_parameter< int >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppGetLocalContinuityMetaCriterion(data, conf, Rn, k));
    return rcpp_result_gen;
END_RCPP
}
// RcppGetLocalContinuityMetaCriterionByVector
Rcpp::List RcppGetLocalContinuityMetaCriterionByVector(arma::mat& data, arma::mat& conf, int Rn, int k);
RcppExport SEXP _RcppHSLocalMDS_RcppGetLocalContinuityMetaCriterionByVector(SEXP dataSEXP, SEXP confSEXP, SEXP RnSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type conf(confSEXP);
    Rcpp::traits::input_parameter< int >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppGetLocalContinuityMetaCriterionByVector(data, conf, Rn, k));
    return rcpp_result_gen;
END_RCPP
}
// RcppOptimHSMds
Rcpp::List RcppOptimHSMds(arma::mat& data, arma::mat& conf, unsigned int& Rn, double& Gamma, int& maxIt, const std::string& optMethod);
RcppExport SEXP _RcppHSLocalMDS_RcppOptimHSMds(SEXP dataSEXP, SEXP confSEXP, SEXP RnSEXP, SEXP GammaSEXP, SEXP maxItSEXP, SEXP optMethodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type conf(confSEXP);
    Rcpp::traits::input_parameter< unsigned int& >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< double& >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< int& >::type maxIt(maxItSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type optMethod(optMethodSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOptimHSMds(data, conf, Rn, Gamma, maxIt, optMethod));
    return rcpp_result_gen;
END_RCPP
}
// RcppOptimHSLocalMds
Rcpp::List RcppOptimHSLocalMds(arma::mat& data, arma::mat& conf, arma::imat& neighborhood, arma::imat& notNeighborhood, unsigned int& Rn, double& tt, double& Gamma, int& maxIt, const std::string& optMethod);
RcppExport SEXP _RcppHSLocalMDS_RcppOptimHSLocalMds(SEXP dataSEXP, SEXP confSEXP, SEXP neighborhoodSEXP, SEXP notNeighborhoodSEXP, SEXP RnSEXP, SEXP ttSEXP, SEXP GammaSEXP, SEXP maxItSEXP, SEXP optMethodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type conf(confSEXP);
    Rcpp::traits::input_parameter< arma::imat& >::type neighborhood(neighborhoodSEXP);
    Rcpp::traits::input_parameter< arma::imat& >::type notNeighborhood(notNeighborhoodSEXP);
    Rcpp::traits::input_parameter< unsigned int& >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< double& >::type tt(ttSEXP);
    Rcpp::traits::input_parameter< double& >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< int& >::type maxIt(maxItSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type optMethod(optMethodSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOptimHSLocalMds(data, conf, neighborhood, notNeighborhood, Rn, tt, Gamma, maxIt, optMethod));
    return rcpp_result_gen;
END_RCPP
}
// RcppHSMDS
Rcpp::List RcppHSMDS(arma::mat& data, arma::mat conf, unsigned int Rn, unsigned int Kquality, bool verbose, bool applyHiperbolicSmoothing, double gamma, unsigned int n_gamma, double rho, int maxIt, const std::string optMethod);
RcppExport SEXP _RcppHSLocalMDS_RcppHSMDS(SEXP dataSEXP, SEXP confSEXP, SEXP RnSEXP, SEXP KqualitySEXP, SEXP verboseSEXP, SEXP applyHiperbolicSmoothingSEXP, SEXP gammaSEXP, SEXP n_gammaSEXP, SEXP rhoSEXP, SEXP maxItSEXP, SEXP optMethodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type conf(confSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type Kquality(KqualitySEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type applyHiperbolicSmoothing(applyHiperbolicSmoothingSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_gamma(n_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type maxIt(maxItSEXP);
    Rcpp::traits::input_parameter< const std::string >::type optMethod(optMethodSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppHSMDS(data, conf, Rn, Kquality, verbose, applyHiperbolicSmoothing, gamma, n_gamma, rho, maxIt, optMethod));
    return rcpp_result_gen;
END_RCPP
}
// RcppHSlocalMDS
Rcpp::List RcppHSlocalMDS(arma::mat& data, arma::mat conf, unsigned int Rn, unsigned int Kproj, unsigned int Kquality, bool verbose, bool selectBetterUnitFree, double smallerUnitFree, unsigned int n_t, double ratio, bool applyHiperbolicSmoothing, double gamma, unsigned int n_gamma, double rho, int maxIt, const std::string optMethod);
RcppExport SEXP _RcppHSLocalMDS_RcppHSlocalMDS(SEXP dataSEXP, SEXP confSEXP, SEXP RnSEXP, SEXP KprojSEXP, SEXP KqualitySEXP, SEXP verboseSEXP, SEXP selectBetterUnitFreeSEXP, SEXP smallerUnitFreeSEXP, SEXP n_tSEXP, SEXP ratioSEXP, SEXP applyHiperbolicSmoothingSEXP, SEXP gammaSEXP, SEXP n_gammaSEXP, SEXP rhoSEXP, SEXP maxItSEXP, SEXP optMethodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type conf(confSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type Kproj(KprojSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type Kquality(KqualitySEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type selectBetterUnitFree(selectBetterUnitFreeSEXP);
    Rcpp::traits::input_parameter< double >::type smallerUnitFree(smallerUnitFreeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_t(n_tSEXP);
    Rcpp::traits::input_parameter< double >::type ratio(ratioSEXP);
    Rcpp::traits::input_parameter< bool >::type applyHiperbolicSmoothing(applyHiperbolicSmoothingSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_gamma(n_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type maxIt(maxItSEXP);
    Rcpp::traits::input_parameter< const std::string >::type optMethod(optMethodSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppHSlocalMDS(data, conf, Rn, Kproj, Kquality, verbose, selectBetterUnitFree, smallerUnitFree, n_t, ratio, applyHiperbolicSmoothing, gamma, n_gamma, rho, maxIt, optMethod));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppHSLocalMDS_getNeighborhoodMatrix", (DL_FUNC) &_RcppHSLocalMDS_getNeighborhoodMatrix, 3},
    {"_RcppHSLocalMDS_getNeighborhoodVector", (DL_FUNC) &_RcppHSLocalMDS_getNeighborhoodVector, 2},
    {"_RcppHSLocalMDS_getEuclideanDistanceMatrix", (DL_FUNC) &_RcppHSLocalMDS_getEuclideanDistanceMatrix, 1},
    {"_RcppHSLocalMDS_getParameterT", (DL_FUNC) &_RcppHSLocalMDS_getParameterT, 3},
    {"_RcppHSLocalMDS_getHSLocalMdsStress", (DL_FUNC) &_RcppHSLocalMDS_getHSLocalMdsStress, 7},
    {"_RcppHSLocalMDS_getHSLocalMdsStressGradient", (DL_FUNC) &_RcppHSLocalMDS_getHSLocalMdsStressGradient, 7},
    {"_RcppHSLocalMDS_getHSMdsStress", (DL_FUNC) &_RcppHSLocalMDS_getHSMdsStress, 4},
    {"_RcppHSLocalMDS_getHSMdsStressNormalized", (DL_FUNC) &_RcppHSLocalMDS_getHSMdsStressNormalized, 4},
    {"_RcppHSLocalMDS_getHSMdsStressGradient", (DL_FUNC) &_RcppHSLocalMDS_getHSMdsStressGradient, 4},
    {"_RcppHSLocalMDS_RcppGetLocalContinuityMetaCriterion", (DL_FUNC) &_RcppHSLocalMDS_RcppGetLocalContinuityMetaCriterion, 4},
    {"_RcppHSLocalMDS_RcppGetLocalContinuityMetaCriterionByVector", (DL_FUNC) &_RcppHSLocalMDS_RcppGetLocalContinuityMetaCriterionByVector, 4},
    {"_RcppHSLocalMDS_RcppOptimHSMds", (DL_FUNC) &_RcppHSLocalMDS_RcppOptimHSMds, 6},
    {"_RcppHSLocalMDS_RcppOptimHSLocalMds", (DL_FUNC) &_RcppHSLocalMDS_RcppOptimHSLocalMds, 9},
    {"_RcppHSLocalMDS_RcppHSMDS", (DL_FUNC) &_RcppHSLocalMDS_RcppHSMDS, 11},
    {"_RcppHSLocalMDS_RcppHSlocalMDS", (DL_FUNC) &_RcppHSLocalMDS_RcppHSlocalMDS, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppHSLocalMDS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
