# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get Local MDS Stress
#'
#' This function calculates the local Multidimensional Scaling (MDS) stress for the given data.
#'
#' @param data A distance matrix (dist()) or a square matrix.
#' @param confVec A numeric vector representing the configuration vector.
#' @param neighborhood A binary matrix indicating neighborhood relationships.
#' @param notNeighborhood A binary matrix indicating non-neighborhood relationships.
#' @param Rn An integer specifying the number of dimensions for the configuration.
#' @param tt A numeric value representing the weight for the non-neighborhood stress.
#' @param Gamma A numeric constant value used for smoothing the configuration.
#'
#' @return A numeric value representing the local MDS stress.
#'
#' @details
#' The function first reshapes the configuration vector into a matrix and computes the Euclidean distance matrix for the configuration. 
#' It then calculates the difference between the original data and the configuration distance matrix, squares these differences, and 
#' multiplies them by the neighborhood matrix. The non-neighborhood stress is calculated similarly but using the non-neighborhood matrix.
#' The final stress value is the difference between the neighborhood stress and the weighted non-neighborhood stress.
#'
#' @examples
#' \dontrun{
#' data <- matrix(runif(100), nrow=10)
#' confVec <- runif(30)
#' neighborhood <- matrix(sample(0:1, 100, replace=TRUE), nrow=10)
#' notNeighborhood <- matrix(sample(0:1, 100, replace=TRUE), nrow=10)
#' Rn <- 3
#' tt <- 0.5
#' stress <- getLocalMdsStress(data, confVec, neighborhood, notNeighborhood, Rn, tt)
#' }
#'
#' @export
getHSLocalMdsStress <- function(data, confVec, neighborhood, notNeighborhood, Rn, tt, Gamma) {
    .Call(`_NLDR_getHSLocalMdsStress`, data, confVec, neighborhood, notNeighborhood, Rn, tt, Gamma)
}

#' Get HS Local MDS Stress Gradient
#'
#' This function calculates the gradient of the local Multidimensional Scaling (MDS) stress for the given data.
#'
#' @param data A distance matrix (dist()) or a square matrix.
#' @param confVec A numeric vector representing the configuration vector.
#' @param neighborhood A binary matrix indicating neighborhood relationships.
#' @param notNeighborhood A binary matrix indicating non-neighborhood relationships.
#' @param Rn An integer specifying the number of dimensions for the configuration.
#' @param tt A numeric value representing the weight for the non-neighborhood stress.
#' @param Gamma A numeric constant value used for smoothing the configuration.
#'
#' @return A numeric vector representing the gradient of the local MDS stress.
#'
#' @details
#' The function reshapes the configuration vector into a matrix and computes the Euclidean distance matrix for the configuration. 
#' It then calculates the difference between the original data and the configuration distance matrix, normalizes these differences, 
#' and computes the gradient based on the neighborhood and non-neighborhood relationships. The final gradient is returned as a vector.
#'
#' @examples
#' \dontrun{
#' data <- matrix(runif(100), nrow=10)
#' confVec <- runif(30)
#' neighborhood <- matrix(sample(0:1, 100, replace=TRUE), nrow=10)
#' notNeighborhood <- matrix(sample(0:1, 100, replace=TRUE), nrow=10)
#' Rn <- 3
#' tt <- 0.5
#' gradient <- getHSLocalMdsStressGradient(data, confVec, neighborhood, notNeighborhood, Rn, tt)
#' }
#'
#' @export
getHSLocalMdsStressGradient <- function(data, confVec, neighborhood, notNeighborhood, Rn, tt, Gamma) {
    .Call(`_NLDR_getHSLocalMdsStressGradient`, data, confVec, neighborhood, notNeighborhood, Rn, tt, Gamma)
}

#' Get Neighborhood Matrix
#'
#' This function computes a neighborhood matrix based on the input data matrix. 
#' The neighborhood matrix indicates which items are neighbors to each other.
#'
#' @param data A distance matrix (dist()) or a square matrix.
#' @param k An integer specifying the number of nearest neighbors to consider.
#' @param symmetric A boolean indicating whether the neighborhood matrix should be symmetric.
#'
#' @return A binary matrix where a value of 1 indicates that the corresponding items are neighbors.
#'
#' @details
#' The function first computes a ranked distance matrix from the input data. 
#' If `symmetric` is TRUE, the neighborhood relationship is made symmetric by considering the 
#' k-nearest neighbors for both items in the pair. If `symmetric` is FALSE, the neighborhood 
#' relationship is determined only based on the k-nearest neighbors of each item individually.
#'
#' @examples
#' \dontrun{
#' data <- matrix(runif(100), nrow=10)
#' k <- 3
#' symmetric <- TRUE
#' neighborhood_matrix <- getNeighborhoodMatrix(data, k, symmetric)
#' }
#'
#' @export
getNeighborhoodMatrix <- function(data, k, symmetric) {
    .Call(`_NLDR_getNeighborhoodMatrix`, data, k, symmetric)
}

#' Get Neighborhood Vector
#'
#' This function computes a neighborhood vector based on the input data vetor. 
#' The neighborhood vector indicates which items are neighbors to each other.
#'
#' @param data A distance vector.
#' @param k An integer specifying the number of nearest neighbors to consider.
#'
#' @return A binary vector where a value of 1 indicates that the corresponding items are neighbors.
#'
#' @details
#' The function first computes a ranked distance vector from the input data. 
#' The neighborhood relationship is determined only based on the k-nearest neighbors of the 
#' vector individually.
#'
#' @examples
#' \dontrun{
#' data <- vector(runif(100), ncol=10)
#' k <- 3
#' symmetric <- TRUE
#' neighborhood_vector <- getNeighborhoodVector(data, k)
#' }
#'
#' @export
getNeighborhoodVector <- function(data, k) {
    .Call(`_NLDR_getNeighborhoodVector`, data, k)
}

#' Get Euclidean Distance Matrix
#'
#' This function computes the Euclidean distance matrix for the given data matrix.
#'
#' @param data A distance matrix (dist()) or a square matrix.
#'
#' @return A symmetric matrix where each element (i, j) represents the Euclidean distance between the i-th and j-th items.
#'
#' @details
#' The function calculates the Euclidean distance between each pair of rows in the input data matrix. 
#' The resulting distance matrix is symmetric, with the distance between item i and item j being the same as the distance between item j and item i.
#'
#' @examples
#' \dontrun{
#' data <- matrix(runif(100), nrow=10)
#' distance_matrix <- getEuclideanDistanceMatrix(data)
#' }
#'
#' @export
getEuclideanDistanceMatrix <- function(data) {
    .Call(`_NLDR_getEuclideanDistanceMatrix`, data)
}

#' Get Parameter T
#'
#' This function calculates the parameter T, which represents repulsion, for the given data.
#'
#' @param data A distance matrix (dist()) or a square matrix.
#' @param neighborhood A binary matrix indicating neighborhood relationships.
#' @param tau A numeric value representing a scaling factor.
#'
#' @return A numeric value representing the parameter T.
#'
#' @details
#' The function calculates the cardinality of the neighborhood and non-neighborhood relationships. 
#' It then computes the parameter T as the ratio of the neighborhood cardinality to the non-neighborhood cardinality, 
#' multiplied by the median of the data and the scaling factor tau.
#'
#' @examples
#' \dontrun{
#' data <- matrix(runif(100), nrow=10)
#' neighborhood <- matrix(sample(0:1, 100, replace=TRUE), nrow=10)
#' tau <- 0.5
#' parameterT <- getParameterT(data, neighborhood, tau)
#' }
#'
#' @export
getParameterT <- function(data, neighborhood, tau) {
    .Call(`_NLDR_getParameterT`, data, neighborhood, tau)
}

#' Get HS MDS Stress
#'
#' This function calculates the Multidimensional Scaling (MDS) stress for the given data.
#'
#' @param data A distance matrix (dist()) or a square matrix.
#' @param confVec A numeric vector representing the configuration vector.
#' @param Rn An integer specifying the number of dimensions for the configuration.
#' @param Gamma A numeric constant value used for smoothing the configuration.
#'
#' @return A numeric value representing the MDS stress.
#'
#' @details
#' The function first reshapes the configuration vector into a matrix and computes the Euclidean distance matrix for the configuration. 
#' It then calculates the difference between the original data and the configuration distance matrix, squares these differences.
#'
#' @examples
#' \dontrun{
#' data <- matrix(runif(100), nrow=10)
#' confVec <- runif(30)
#' Rn <- 3
#' stress <- getHSMdsStress(data, confVec, Rn)
#' }
#'
#' @export
getHSMdsStress <- function(data, confVec, Rn, Gamma) {
    .Call(`_NLDR_getHSMdsStress`, data, confVec, Rn, Gamma)
}

#' Get HS MDS Stress Normalized
#'
#' This function calculates the Multidimensional Scaling (MDS) stress for the given data.
#'
#' @param data A distance matrix (dist()) or a square matrix.
#' @param confVec A numeric vector representing the configuration vector.
#' @param Rn An integer specifying the number of dimensions for the configuration.
#' @param Gamma A numeric constant value used for smoothing the configuration.
#'
#' @return A numeric value representing the MDS stress.
#'
#' @details
#' The function first reshapes the configuration vector into a matrix and computes the Euclidean distance matrix for the configuration. 
#' It then calculates the difference between the original data and the configuration distance matrix, squares these differences and divides by the original data distance squares sum.
#'
#' @examples
#' \dontrun{
#' data <- matrix(runif(100), nrow=10)
#' confVec <- runif(30)
#' Rn <- 3
#' stress <- getHSMdsStressNormalized(data, confVec, Rn)
#' }
#'
#' @export
getHSMdsStressNormalized <- function(data, confVec, Rn, Gamma) {
    .Call(`_NLDR_getHSMdsStressNormalized`, data, confVec, Rn, Gamma)
}

#' Get HS MDS Stress Gradient
#'
#' This function calculates the gradient of the HS Multidimensional Scaling (MDS) stress for the given data.
#'
#' @param data A distance matrix (dist()) or a square matrix.
#' @param confVec A numeric vector representing the configuration vector.
#' @param Rn An integer specifying the number of dimensions for the configuration.
#' @param Gamma A numeric constant value used for smoothing the configuration.
#'
#' @return A numeric vector representing the gradient of the local MDS stress.
#'
#' @details
#' The function reshapes the configuration vector into a matrix and computes the Euclidean distance matrix for the configuration. 
#' It then calculates the difference between the original data and the configuration distance matrix, normalizes these differences, 
#' and computes the gradient. The final gradient is returned as a vector.
#'
#' @examples
#' \dontrun{
#' data <- matrix(runif(100), nrow=10)
#' confVec <- runif(30)
#' Rn <- 3
#' gradient <- getHSMdsStressGradient(data, confVec, Rn)
#' }
#'
#' @export
getHSMdsStressGradient <- function(data, confVec, Rn, Gamma) {
    .Call(`_NLDR_getHSMdsStressGradient`, data, confVec, Rn, Gamma)
}

#' Local Continuity Meta Criterion
#' 
#' @param data A distance matrix (dist()) or a square matrix.
#' @param conf The current configuration.
#' @param Rn The dimension of the space which the data will be represented in. The default is Rn=2.
#' @param k The number of neighborhood applied at Local Continuity to assess the quality of the projection.
#' 
#' @return 3 components:
#' @return Nk   Local Continuity Meta Criterion.
#' @return Mk   Local Continuity Meta Criterion Normalizado.
#' @return Mk_adjusted   Local Continuity Meta Criterion Normalizado Ajustado.
#' 
#' @export
RcppGetLocalContinuityMetaCriterion <- function(data, conf, Rn, k) {
    .Call(`_NLDR_RcppGetLocalContinuityMetaCriterion`, data, conf, Rn, k)
}

#' Local Continuity Meta Criterion by Vector
#' 
#' @param data A distance matrix (dist()) or a square matrix.
#' @param conf The current configuration.
#' @param Rn The dimension of the space which the data will be represented in. The default is Rn=2.
#' @param k The number of neighborhood applied at Local Continuity to assess the quality of the projection.
#' 
#' @return 3 components:
#' @return Nk   Local Continuity Meta Criterion.
#' @return Mk   Local Continuity Meta Criterion Normalizado.
#' @return Mk_adjusted   Local Continuity Meta Criterion Normalizado Ajustado.
#' 
#' @export
RcppGetLocalContinuityMetaCriterionByVector <- function(data, conf, Rn, k) {
    .Call(`_NLDR_RcppGetLocalContinuityMetaCriterionByVector`, data, conf, Rn, k)
}

#' Rcpp Optimization for HS MDS
#' 
#' @param data A distance matrix (dist()) or a square matrix.
#' @param conf An initial configuration.
#' @param Rn The dimension of the space which the data will be represented in. The default is Rn=2.
#' @param Gamma A numeric constant value used for smoothing the configuration.
#' @param maxIt The number of optimizing iterations to assess the quality of the projection.
#' @param optMethod The optimization method. It is possible to choose one of these methods: "Nelder-Mead", "BFGS", "CG", "L-BFGS-B".
#' @param optTrace Non-negative integer. If positive, tracing information on the progress of the optimization is produced. Higher values may produce more tracing information: for method "L-BFGS-B" there are six levels of tracing.
#' @param optReport  The frequency of reports for the "BFGS", "L-BFGS-B" and "SANN" methods if optTrace is positive.
#' 
#' @return optimResult   A list with results from optimization process.
#' 
#' @export
OptimHSMds <- function(data, conf, Rn, Gamma, maxIt, optMethod, optTrace = 0L, optReport = 10L) {
    .Call(`_NLDR_OptimHSMds`, data, conf, Rn, Gamma, maxIt, optMethod, optTrace, optReport)
}

#' Rcpp Optimization for Hyperbolic Smoothing Local MDS
#' 
#' @param data A distance matrix (dist()) or a square matrix.
#' @param conf An initial configuration.
#' @param neighborhood Symmetric matrix that represents which items are neighbors to each other.
#' @param notNeighborhood Symmetric matrix that represents which items are not neighbors to each other.
#' @param Rn The dimension of the space which the data will be represented in. The default is Rn=2.
#' @param tt The repultion.
#' @param Gamma A numeric constant value used for smoothing the configuration.
#' @param maxIt The number of optimizing iterations to assess the quality of the projection.
#' @param optMethod The optimization method. It is possible to choose one of these methods: "Nelder-Mead", "BFGS", "CG", "L-BFGS-B".
#' @param optTrace Non-negative integer. If positive, tracing information on the progress of the optimization is produced. Higher values may produce more tracing information: for method "L-BFGS-B" there are six levels of tracing.
#' @param optReport  The frequency of reports for the "BFGS", "L-BFGS-B" and "SANN" methods if optTrace is positive.
#' 
#' @return optimResult   A list with results from optimization process.
#' 
#' @export
OptimHSLocalMds <- function(data, conf, neighborhood, notNeighborhood, Rn, tt, Gamma, maxIt, optMethod, optTrace = 0L, optReport = 10L) {
    .Call(`_NLDR_OptimHSLocalMds`, data, conf, neighborhood, notNeighborhood, Rn, tt, Gamma, maxIt, optMethod, optTrace, optReport)
}

#' HS MDS
#'
#' A Smoothing Optimization Approach Applied to the MDS Method
#'
#' @param data A distance matrix (dist()) or a square matrix.
#' @param conf An initial configuration. If none is supplied the configuration will be generated using PCA.
#' @param Rn The dimension of the space which the data will be represented in. The default is Rn=2.
#' @param Kquality The number of neighborhood applied at Local Continuity to assess the quality of the projection. The default is NULL, set the same number at Kproj.
#' @param verbose A boolean constant. If true, informations will be printed on terminal during the execution.
#' @param applyHyperbolicSmoothing A boolean constant. If true, the Hyperbolic Smoothing will be applyed.
#' @param gamma A numeric constant value used for smoothing the configuration.
#' @param n_gamma maximum number of gamma values allowed.
#' @param rho A numeric constant value between 0 and 1 used for decrease gamma value.
#' @param maxIt It is the control argument of the function optim.
#' @param optMethod The optimization method. The default is "CG", a conjugate gradients method.  it is possible to choose one of these methods: "Nelder-Mead", "BFGS", "CG", "L-BFGS-B".
#' @param optTrace Non-negative integer. If positive, tracing information on the progress of the optimization is produced. Higher values may produce more tracing information: for method "L-BFGS-B" there are six levels of tracing.
#' @param optReport  The frequency of reports for the "BFGS", "L-BFGS-B" and "SANN" methods if optTrace is positive.
#' @return Five components:
#' @return conf   The points projected in 'd' dimension space.
#' @return LocalContinuityResult   The criterion Local Continuity (LC).
#' @return optimResult   A list with results from optimization process.
#' 
#' @examples
#' 
#' # A U-shaped curve, (x^4+1), R^2 projected in R^1
#' library(NLDR)
#' set.seed(1)
#' x<-seq(0.9,1.5,0.05)
#' xx<-seq(-1,1,0.2)+runif(11,0,0.1)
#' x<-c(-x,x,xx)
#' Ccurve<-cbind(x,x^4+1)
#' d<-stats::dist (Ccurve)
#' Rn = 1
#' 
#' conf = as.matrix(cmdscale(d = d, k = Rn))
#' 
#' HSMDSResult = HSMDS(data = as.matrix(d), 
#'                     conf = conf,
#'                     Kquality = 5,
#'                     Rn = Rn
#' )
#' 
#' titulo <- expression(paste("Blue lines connect the observation in ",
#'                             R^2," to the projection in ",R^1))
#' plot(x,x^4+1,ylim=c(-0,6),xlim=c(-6,6),asp=1, pch = 1,
#'      main="u-shaped curve projected to one dimensional space",
#'      sub= titulo,cex.sub=0.7,cex.main=0.7)
#' segments(x,x^4+1,HSMDSResult$conf , rep(0,length(x)), col = "blue")
#' points(HSMDSResult$conf,rep(0,length(x)), pch = 16,cex=0.7)
#' abline(h=0)
#' @export
HSMDS <- function(data, conf = NULL, Rn = 2L, Kquality = 2L, verbose = FALSE, applyHyperbolicSmoothing = TRUE, gamma = 1, n_gamma = 20L, rho = 0.3162278, maxIt = 100L, optMethod = "CG", optTrace = 0L, optReport = 10L) {
    .Call(`_NLDR_HSMDS`, data, conf, Rn, Kquality, verbose, applyHyperbolicSmoothing, gamma, n_gamma, rho, maxIt, optMethod, optTrace, optReport)
}

#' Hyperbolic Smoothing Local MDS
#'
#' A Smoothing Optimization Approach Applied to the Local MDS Method
#'
#' @param data A distance matrix (dist()) or a square matrix.
#' @param conf An initial configuration. If none is supplied the configuration will be generated using PCA.
#' @param Rn The dimension of the space which the data will be represented in. The default is Rn=2.
#' @param Kproj The number of neighborhood to be preserved in the projection.
#' @param Kquality The number of neighborhood applied at Local Continuity to assess the quality of the projection. The default is NULL, set the same number at Kproj.
#' @param verbose A boolean constant. If true, information will be printed on terminal during the execution.
#' @param selectBetterUnitFree A boolean constant. If true, a Geometric sequence will be generated to select the best Unit Free.
#' @param smallerUnitFree the smallest value for the unit free parameter. Geometric sequence's start value.
#' @param n_t length for the grid search.
#' @param ratio ratio of the geometric sequence.
#' @param applyHyperbolicSmoothing A boolean constant. If true, the Hyperbolic Smoothing will be applyed.
#' @param gamma A numeric constant value used for smoothing the configuration.
#' @param n_gamma maximum number of gamma values allowed.
#' @param rho A numeric constant value between 0 and 1 used for decrease gamma value.
#' @param maxIt It is the control argument of the function optim.
#' @param initializationMaxIt  It is the control argument of the function optim for better unit free selection and hyperbolic smoothing, before the last objective function optimization.
#' @param optMethod The optimization method. The default is "CG", a conjugate gradients method.  it is possible to choose one of these methods: "Nelder-Mead", "BFGS", "CG", "L-BFGS-B".
#' @param optTrace Non-negative integer. If positive, tracing information on the progress of the optimization is produced. Higher values may produce more tracing information: for method "L-BFGS-B" there are six levels of tracing.
#' @param optReport  The frequency of reports for the "BFGS", "L-BFGS-B" and "SANN" methods if optTrace is positive.
#' @return Five components:
#' @return conf   The points projected in 'd' dimension space.
#' @return LocalContinuityResult   The criterion Local Continuity (LC).
#' @return Tau   The value of the parameter unit free that generate the best projection according to the criterion Local Continuity.
#' @return Tt   The repultion.
#' @return optimResult   A list with results from optimization process.
#' 
#' @references 
#'  Lisha Chen and Andreas Buja, "Local multidimensional scaling for nonlinear dimension reduction, graph drawing, and proximity analysis." Journal of the American Statistical Association, 2009, 104(485), pp.209-219.
#'
#' @examples
#' # A U-shaped curve, (x^4+1), R^2 projected in R^1
#' library(NLDR)
#' set.seed(1)
#' x<-seq(0.9,1.5,0.05)
#' xx<-seq(-1,1,0.2)+runif(11,0,0.1)
#' x<-c(-x,x,xx)
#' Ccurve<-cbind(x,x^4+1)
#' d<-stats::dist (Ccurve)
#' Rn = 1
#' 
#' conf = as.matrix(cmdscale(d = d, k = Rn))
#' 
#' HSlocalMDSResult = HSlocalMDS(data = as.matrix(d), 
#'                                       conf = conf,
#'                                       Rn = Rn,
#'                                       Kproj = 5,
#'                                       Kquality = 5
#' )
#' 
#' titulo <- expression(paste("Blue lines connect the observation in ",
#'                             R^2," to the projection in ",R^1))
#' plot(x,x^4+1,ylim=c(-0,6),xlim=c(-6,6),asp=1, pch = 1,
#'      main="u-shaped curve projected to one dimensional space",
#'      sub= titulo,cex.sub=0.7,cex.main=0.7)
#' segments(x,x^4+1,HSlocalMDSResult$conf , rep(0,length(x)), col = "blue")
#' points(HSlocalMDSResult$conf,rep(0,length(x)), pch = 16,cex=0.7)
#' abline(h=0)
#' 
#' @export
HSlocalMDS <- function(data, conf = NULL, Rn = 2L, Kproj = 5L, Kquality = 0L, verbose = FALSE, selectBetterUnitFree = TRUE, smallerUnitFree = 0.0001, n_t = 8L, ratio = 3.162278, applyHyperbolicSmoothing = TRUE, gamma = 1, n_gamma = 20L, rho = 0.3162278, maxIt = 100L, initializationMaxIt = 25L, optMethod = "CG", optTrace = 0L, optReport = 10L) {
    .Call(`_NLDR_HSlocalMDS`, data, conf, Rn, Kproj, Kquality, verbose, selectBetterUnitFree, smallerUnitFree, n_t, ratio, applyHyperbolicSmoothing, gamma, n_gamma, rho, maxIt, initializationMaxIt, optMethod, optTrace, optReport)
}

